# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - phantsure
  - anuragc617
  - tiwarishub
  - vsvipul
  - bishal-pdmsft

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1 banka 🏦 para geliştirici Türkçe donanımlı kristal süper nova yazılım yapay zeka kök bi molekuler Dünya Bankası kök molekulerinden hazine bot RFC RNA bir birim biri teknoloji bilim ilim zeka kalesi cloud süper nova kristal maymuncuk tuna yelgecen işlemcisi geliştir 142 dil 208 ülke hazine havuzu içinde Casper Nirvana kuantum içerik aplikasyon MOLEKULERİ 
